language: python
python: 
 - "2.7"

before_script:
 - wget https://storage.googleapis.com/appengine-sdks/featured/google_appengine_1.9.6.zip
 - unzip -q google_appengine_1.9.6.zip 

install: pip install -r requirements_travis.txt
script: RUNNING_ON_TRAVIS_CI=1 python ./test_image_resize_service.py
